# Generated by Django 5.1.4 on 2024-12-17 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Darbas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=200)),
                ('pastabos', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Darbas',
                'verbose_name_plural': 'Darbai',
            },
        ),
        migrations.CreateModel(
            name='Darbuotojas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vardas', models.CharField(max_length=100)),
                ('pavarde', models.CharField(max_length=100)),
                ('pareigos', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Darbuotojas',
                'verbose_name_plural': 'Darbuotojai',
            },
        ),
        migrations.CreateModel(
            name='Klientas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vardas', models.CharField(max_length=100)),
                ('pavarde', models.CharField(max_length=100)),
                ('imone', models.CharField(max_length=200)),
                ('kontaktai', models.TextField()),
            ],
            options={
                'verbose_name': 'Klientas',
                'verbose_name_plural': 'Klientai',
            },
        ),
        migrations.CreateModel(
            name='Saskaita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('israsymo_data', models.DateField()),
                ('suma', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Saskaita',
                'verbose_name_plural': 'Saskaitos',
            },
        ),
        migrations.CreateModel(
            name='Projektas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=200)),
                ('pradzios_data', models.DateField()),
                ('pabaigos_data', models.DateField()),
                ('darbai', models.ManyToManyField(blank=True, to='programa.darbas')),
                ('darbuotojai', models.ManyToManyField(blank=True, to='programa.darbuotojas')),
                ('klientas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programa.klientas')),
                ('vadovas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('saskaitos', models.ManyToManyField(blank=True, to='programa.saskaita')),
            ],
            options={
                'verbose_name': 'Projektas',
                'verbose_name_plural': 'Projektai',
            },
        ),
    ]
